---
output:
  html_document
toc-title: 'Results - Downsampling ChiSense-12 (Appendix S2)'

---

<!-- loading packages, user-defined functions and datasets -->
```{r echo=FALSE, warning=FALSE, message=FALSE, cache=FALSE, include=FALSE}
lib <- c(
  "ggpattern",
  "beepr", 
  "magrittr", 
  "tidyverse",
  "tokenizers",
  "jsonlite",
  "knitr",
  "ggthemes",
  "lme4",
  "sjPlot"
)

lapply(lib, require, character.only = TRUE)
rm(lib)

load(file="ws_downsampled.RData")

# load other libraries and user-defined functions
sapply(
  c("requirements.R", "my_funs.R"),
  source
)
```

<!-- additional functions/objects -->
```{r echo = FALSE, eval = FALSE}
# use this chunk when not loading ws environment above
path_results <- str_replace(getwd(), "r_project$", "results/ChiSense-12_for_nlm/1nn")

full_models <- list.dirs(path = path_results, full.names = FALSE) %>%
  str_subset("_random|_downsample", negate = TRUE) %>%
  {.[-1]}

downsample_models <- list.dirs(path = path_results, full.names = FALSE) %>%
  str_subset("_downsample") 

test_data <- read_csv("test_utterances.csv") %>%
  mutate(utterance = utterance %>%
           tolower)

bert_output <- list()
for (model_type in full_models) {
  for (target_label in c("band", "bat", "bow", "button", 
                         "chicken",  "glasses", "letter", "line",
                         "nail")) {
    output <- readLines(paste0(path_results, "/", model_type, "/",
                               target_label, ".jsonl")) %>%
      lapply(fromJSON) %>%
      lapply(unlist) %>%
      bind_rows %>%
      unite("utterance", starts_with("tokens"), na.rm = TRUE,  sep = " ") %>% 
      (function(df) {
        df %>%
          select(gold, utterance, matches1, matches3) %>%
          rename(sense = matches1,
                 cosine = matches3) %>%
          rbind(
            df %>%
              select(gold, utterance, matches2, matches4) %>%
              rename(sense = matches2,
                     cosine = matches4)
          )
      }) %>%
      mutate(utterance = utterance %>%
               str_replace_all("<92>", "’")) %>%
      left_join(., test_data, by = "utterance") %>%
      mutate(model = model_type) %>%
      arrange(model_type, study, experiment, condition, utterance) 
    
    bert_output %<>%
      c(list(output))
  }
}

bert_output %<>%
  bind_rows %>%
  mutate(sample = 1) %>%
  mutate(model_type = "full")

bert_output_downsample <- list()
for (model_type in downsample_models) {
  for (target_label in c("band", "bat", "bow", "button", 
                         "chicken",  "glasses", "letter", "line",
                         "nail")) {
    output <- readLines(paste0(path_results, "/", model_type, "/",
                               target_label, ".jsonl")) %>%
      lapply(fromJSON) %>%
      lapply(unlist) %>%
      bind_rows %>%
      unite("utterance", starts_with("tokens"), na.rm = TRUE,  sep = " ") %>% 
      (function(df) {
        df %>%
          select(gold, utterance, matches1, matches3) %>%
          rename(sense = matches1,
                 cosine = matches3) %>%
          rbind(
            df %>%
              select(gold, utterance, matches2, matches4) %>%
              rename(sense = matches2,
                     cosine = matches4)
          )
      }) %>%
      mutate(utterance = utterance %>%
               str_replace_all("<92>", "’")) %>%
      left_join(., test_data, by = "utterance") %>%
      mutate(model = model_type) %>%
      arrange(model_type, study, experiment, condition, utterance) 
    
    bert_output_downsample %<>%
      c(list(output))
  }
}

bert_output_downsample %<>%
  bind_rows %>%
  separate(model, c("model", "sample"), sep = "_downsample") %>%
  mutate(model_type = "downsample")

models_names <- c("distilbert-base-uncased","bert-base-uncased", "bert-large-uncased", "bert-large-uncased-whole-word-masking",
             "distilroberta-base","roberta-base", "roberta-large",
             
             "roberta-med-small-1M-2", "roberta-base-10M-2", "roberta-base-100M-2", "roberta-base-1B-3",
      
            "albert-base-v1", "albert-large-v1", "albert-xlarge-v1", "albert-xxlarge-v1",
            "albert-base-v2", "albert-large-v2", "albert-xlarge-v2",  "albert-xxlarge-v2", 
            
            "deberta-base", "deberta-large", "deberta-xlarge",
            "deberta-v2-xlarge", "deberta-v2-xxlarge", 
            "deberta-v3-small", "deberta-v3-base", "deberta-v3-large",
            
            "babyberta-ao-childes", "babyberta-ao-newsela", "babyberta-wikipedia-1",
            "babyberta-ao-childes-ao-newsela-wikipedia-1", 
            
            "distilgpt2","openai-gpt", "gpt2", "gpt2-medium", "gpt2-large", "gpt2-xl",
            
            "transfo-xl-wt103",
            
            "ctrl", 
            
            "t5-small", "t5-base", "t5-large",
            
            "xlnet-base-cased", "xlnet-large-cased",
            
            "elmo"
            )

family_codes <- tibble(
  models = models_names) %>%
  mutate(size = c(66, 110, 340, 340, # bert
                  82, 125, 355, # roberta
                  45, 125, 125, 125, # minibertas
                  11, 17, 58, 223, # albert v1
                  11, 17, 58, 223, # albert v2
                  140, 400, 750, # deberta 
                  900, 1500, # deberta v2
                  141, 184, 434, # deberta v3
                  8,8,8,8, # babyberta
                  82, 116, 124, 355, 774, 1558, # gpt
                  284, # transfo-xl
                  1630, # ctrl
                  35, 110, 335, # t5
                  117, 360, # xlnet
                  93 # elmo
                  )) %>%
  mutate(pretraining =
    c(16, 16, 16, 16, # bert
      40, 160, 160, # roberta
      .005, .05, .5, 5, # minibertas
      16, 16, 16, 16, # albert v1
      16, 16, 16, 16, # albert v2
      80, 80, 80, # deberta 
      160, 160, # deberta v2
      160, 160, 160, # deberta v3
      .02,.02,.02,.06, # babyberta
      40, 3, 40, 40, 40, 40, # gpt
      .4, # transfo-xl
      140, # ctrl
      806, 806, 806, # t5
      126, 126, # xlnet
      4.2 # elmo
  )) %>%
  mutate(family = case_when(
    str_detect(models, "^bert-") ~ "bert",
    str_detect(models, "^roberta-") ~ "roberta",
    str_detect(models, "^albert-.*-v1") ~ "albert-v1",
    str_detect(models, "^albert-.*-v2") ~ "albert-v2",
    str_detect(models, "^deberta.*2") ~ "deberta-v2",
    str_detect(models, "^deberta.*3") ~ "deberta-v3",
    str_detect(models, "^deberta[^23]+") ~ "deberta",
    str_detect(models, "^babyberta-") ~ "babyberta",
    str_detect(models, "^gpt|-gpt") ~ "gpt",
    str_detect(models, "^transfo-xl") ~ "transfo-xl",
    str_detect(models, "^ctrl") ~ "ctrl",
    str_detect(models, "^t5-") ~ "t5",
    str_detect(models, "^xlnet-") ~ "xlnet",
    str_detect(models, "^distilbert") ~ "bert",
    str_detect(models, "^distilroberta") ~ "roberta",
    str_detect(models, "^distilgpt2") ~ "gpt",
    str_detect(models, "^elmo") ~ "elmo",
  ))

bert_output %<>%
  rbind(bert_output_downsample)

full_model_levels <- 
  models_names %>%
  rev

family_levels <- c("bert", "albert-v1", "albert-v2", "roberta", "deberta", "deberta-v2", "deberta-v3",
                   "babyberta", "gpt", "transfo-xl", "ctrl", "t5", "xlnet", "elmo")

```

<!-- save plots to folder -->
```{r opts, echo = FALSE}
knitr::opts_chunk$set(
  fig.path = "images/"
)
```


\newline

```{r echo = FALSE}
my_palette <- c(
  "#000000", # bert
  "#4FC601", # albert v1
  "#008941", # albert v2
  "#FFFF00", # roberta
  "#FFDBE5", # deberta
  "#FF4A46", # deberta v2
  "#A30059", # deberta v3
  "#1CE6FF", # babyberta 
  "#0000A6", # gpt
  "#FF34FF", # transfo-xl
  "#6b2a0a", # ctrl
  "#f57402", # t5
  "#848385", # xlnet
  "#7e98f7", # elmo
  "#63FFAC",
  "#B79762",
  "#004D43",
  "#8FB0FF",
  "#997D87",
  "#5A0007",
  "#809693",
  "#FEFFE6",
  "#1B4400",
  "#3B5DFF",
  "#4A3B53",
  "#FF2F80",
  "#61615A",
  "#BA0900",
  "#6B7900",
  "#00C2A0",
  "#FFAA92",
  "#006FA6",
  "#FF90C9",
  "#FF913F",
  "#B903AA",
  "#D16100",
  "#DDEFFF",
  "#000035",
  "#7B4F4B",
  "#A1C299",
  "#300018",
  "#FFB500",
  "#0AA6D8",
  "#013349",
  "#00846F",
  "#372101",
  "#C2FFED",
  "#A079BF",
  "#CC0744",
  "#C0B9B2",
  "#C2FF99",
  "#001E09",
  "#00489C",
  "#6F0062",
  "#0CBD66",
  "#EEC3FF",
  "#456D75",
  "#B77B68",
  "#7A87A1",
  "#788D66",
  "#885578",
  "#FAD09F",
  "#FF8A9A",
  "#D157A0",
  "#BEC459",
  "#456648",
  "#0086ED",
  "#886F4C",
  "#34362D",
  "#B4A8BD",
  "#00A6AA",
  "#452C2C",
  "#636375",
  "#A3C8C9",
  "#938A81",
  "#575329"
)
```

\newline

```{r rabagliati_1_downsample, echo=FALSE, fig.width = 17, fig.height=18, dpi=300}
# Rabagliati - no competition
bert_output %>%
  mutate(value = case_when(
    correct == "bow_weapon" ~ 1,
    correct == "bow_knot" ~ 0,
    correct == "line_order" ~ 1,
    correct == "line_geometry" ~ 0,
    TRUE ~ value
  )) %>% 
  mutate(correct = case_when(
    value == "0" ~ "subordinate",
    value == "1" ~ "primary",
    TRUE ~ correct
  )) %>% 
  mutate(cosine = as.numeric(cosine)) %>%
  filter(study == "Rabagliati", experiment == "a") %>% 
  group_by(model, model_type, sample, utterance) %>%
  filter(cosine == max(cosine)) %>% 
  ungroup %>% 
  mutate(response = gold == sense) %>% 
  mutate(resp = case_when(
    response == TRUE ~ correct,
    response == FALSE & correct == "subordinate" ~ "primary",
    response == FALSE & correct == "primary" ~ "subordinate"
  )) %>% 
  mutate(correct = case_when(
    correct == "subordinate" ~ "Subordinate\nplausible",
    correct == "primary" ~ "Dominant\nplausible"
  )) %>% 
  mutate(model = factor(model),
         model_type = factor(model_type),
         sample = factor(sample),
         condition = factor(condition),
         correct = factor(correct),
         resp = factor(resp)) %>%
  group_by(model, model_type, sample, condition, correct, resp) %>%
  summarise(n = length(resp)) %>% 
  ungroup %>% 
  unite(model, model, model_type, sep = "_") %>%
  unite(model, model, sample, sep = "@") %>% 
  complete(model, condition, correct, resp, fill = list(n= 0)) %>%
  separate(model, c("model", "sample"), sep = "@") %>%
  separate(model, c("model", "model_type"), sep = "_") %>% 
  group_by(model, model_type, sample, condition, correct) %>%
  mutate(tot = sum(n)) %>%
  ungroup %>% 
  mutate(perc = round(n / tot * 100, 0)) %>%
  filter(resp != "subordinate") %>% 
  group_by(model, model_type, condition, correct) %>%
  summarise(mean_perc = mean(perc), sd = sd(perc)) %>%
  ungroup %>%
  rename(perc = mean_perc) %>%
  rename(`Context-sense association` = correct) %>%
  mutate(condition = str_to_title(condition) %>%
           str_replace("$", " context")) %>% 
  left_join(family_codes, by = c("model" = "models")) %>% 
  mutate(model = factor(model, levels = full_model_levels)) %>% 
  mutate(family = factor(family, levels = family_levels)) %>% 
  ggplot(aes(x = model, y = perc, pattern = `Context-sense association`, fill = family)) +
  geom_bar_pattern(data = . %>% filter(model_type == "full"), 
                   stat = "identity", alpha = 0.6, width = .5,
    position = position_dodge(preserve = "single"),
     color = "black", 
     pattern_fill = "dark grey",
     pattern_angle = 45,
                   pattern_density = 0.1,
                   pattern_spacing = 0.025,
                   pattern_key_scale_factor = 0.6) +
  geom_errorbar(data = . %>% 
                  filter(model_type == "downsample") %>%
                  mutate(model_type = "full"), aes(ymin = perc - sd, ymax = perc + sd),
                width=.2, position=position_dodge(1.3), size = 1, colour = "dark red") +
  geom_point(data = . %>% 
                  filter(model_type == "downsample") %>%
                  mutate(model_type = "full"), aes(y = perc), position = position_dodge(1.3), size = 4, colour = "dark red") +
  facet_grid(~ condition, scales = "free_x") +
  scale_y_continuous(limits = c(NA, 100), breaks = seq(0, 100, 25)) +
  geom_hline(yintercept=50, linetype="dashed", size = 0.7) + 
  labs(y = "Dominant sense selection (%)", x = " ") +
  coord_flip() +
  theme_bw() +
  scale_fill_manual(values = my_palette) +
  guides(fill = "none") +
  theme(plot.title = element_text(size = 30), 
        axis.text.x = element_text(size=25, angle = 0, vjust = 0.7),
        axis.text.y = element_text(size=25),
        strip.text = element_text(size=20),
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20),
        axis.title.y = element_text(size=20, margin = margin(t = 0, r = 15, b = 0, l = 0)),
        axis.title.x = element_text(size=30, margin = margin(t = 30, r = 0, b = 0, l = 0)),
        plot.caption = element_text(hjust = 0, size = 25))
```

\newline



```{r rabagliati_2_downsample, echo=FALSE, fig.width=17, fig.height=20, dpi=300}
# Rabagliati - competition
bert_output %>%
  mutate(correct = case_when(
    value == "0" ~ "subordinate",
    value == "1" ~ "primary",
    TRUE ~ correct
  )) %>% 
  mutate(cosine = as.numeric(cosine)) %>%
  filter(study == "Rabagliati", experiment == "b") %>% 
  group_by(model, model_type, sample, utterance) %>%
  filter(cosine == max(cosine)) %>% 
  ungroup %>%  
  mutate(response = gold == sense) %>% mutate(resp = case_when(
    response == TRUE ~ correct,
    response == FALSE & correct == "subordinate" ~ "primary",
    response == FALSE & correct == "primary" ~ "subordinate"
  )) %>% 
  arrange(model, model_type, sample, experiment, utterance, condition) %>% 
  mutate(model = factor(model),
         model_type = factor(model_type),
         sample = factor(sample),
         condition = factor(condition),
         response = factor(response)) %>% 
  group_by(model, model_type, sample, condition, response) %>%
  summarise(n = length(response)) %>%
  ungroup %>%
  unite(model, model, model_type, sep = "_") %>%
  unite(model, model, sample, sep = "@") %>% 
  complete(model, condition, response, fill = list(n= 0)) %>%
  separate(model, c("model", "sample"), sep = "@") %>%
  separate(model, c("model", "model_type"), sep = "_") %>% 
  group_by(model, model_type, sample, condition) %>%
  mutate(tot = sum(n)) %>%
  ungroup %>%
  mutate(perc = round(n / tot * 100, 0)) %>% 
  mutate(sense = case_when(
    response == FALSE & condition == "associated" ~ "primary",
    response == TRUE & condition == "unassociated" ~ "primary",
    TRUE ~ "subordinate"
  )) %>% 
  filter(sense != "subordinate") %>%
  group_by(model, model_type, condition) %>%
  summarise(mean_perc = mean(perc), sd = sd(perc)) %>%
  ungroup %>%
  rename(perc = mean_perc) %>% 
  mutate(condition = case_when(
    condition == "associated" ~ "Subordinate\nplausible",
    condition == "unassociated" ~ "Dominant\nplausible"
  ) %>%
  factor(levels = c("Subordinate\nplausible", "Dominant\nplausible"))) %>%
    left_join(family_codes, by = c("model" = "models")) %>% 
  mutate(model = factor(model, levels = full_model_levels)) %>%
  mutate(family = factor(family, levels = family_levels)) %>%
  rename(Condition = condition) %>%
  ggplot(aes(x = model, y = perc, pattern = Condition, fill = family)) +
  geom_bar_pattern(data = . %>% filter(model_type == "full"), 
                   stat = "identity", alpha = 0.6, width = .5,
    position = position_dodge(preserve = "single"),
     color = "black", 
     pattern_fill = "dark grey",
     pattern_angle = 45,
                   pattern_density = 0.1,
                   pattern_spacing = 0.025,
                   pattern_key_scale_factor = 0.6) +
  geom_errorbar(data = . %>% 
                  filter(model_type == "downsample") %>%
                  mutate(model_type = "full"), aes(ymin = perc - sd, ymax = perc + sd),
                width=.2, position=position_dodge(1.3), size = 1, colour = "dark red") +
  geom_point(data = . %>% 
                  filter(model_type == "downsample") %>%
                  mutate(model_type = "full"), aes(y = perc), position = position_dodge(1.3), size = 4, colour = "dark red") +
  #facet_grid(~ model, scales = "free_x") +
  scale_y_continuous(limits = c(NA, 100), breaks = seq(0, 100, 25)) +
  geom_hline(yintercept=50, linetype="dashed", size = 0.7)+ 
  labs(y = "Dominant sense selection (%)", x = " ") +
  coord_flip() +
  theme_bw() +
  scale_fill_manual(values = my_palette) +
  guides(fill = "none") +
  theme(plot.title = element_text(size = 30), 
        axis.text.x = element_text(size=25, angle = 0, vjust = 0.7),
        axis.text.y = element_text(size=25),
        strip.text = element_text(size=20),
        legend.key.size = unit(3,"line"),
        legend.text = element_text(size = 30),
        legend.title = element_text(size = 30),
        axis.title.y = element_text(size=20, margin = margin(t = 0, r = 15, b = 0, l = 0)),
        axis.title.x = element_text(size=30, margin = margin(t = 30, r = 0, b = 0, l = 0)),
        plot.caption = element_text(hjust = 0, size = 25))
```

\newline



```{r cabiddu_downsample, echo=FALSE, fig.width =17, fig.height=22, dpi=300}
# Cabiddu competition
bert_output %>%
  mutate(correct = case_when(
    value == "0" ~ "subordinate",
    value == "1" ~ "primary",
    TRUE ~ correct
  )) %>%
  mutate(cosine = as.numeric(cosine)) %>%
  filter(study == "Cabiddu", experiment == "a") %>% 
  group_by(model, model_type, sample, utterance) %>%
  filter(cosine == max(cosine)) %>% 
  ungroup %>% 
  mutate(response = gold == sense) %>% mutate(resp = case_when(
    response == TRUE ~ correct,
    response == FALSE & correct == "subordinate" ~ "primary",
    response == FALSE & correct == "primary" ~ "subordinate"
  )) %>% 
  mutate(condition = str_to_title(condition)) %>%
  mutate(model = factor(model),
         model_type = factor(model_type),
         sample = factor(sample),
         condition = factor(condition),
         resp = factor(resp)) %>%
  group_by(model, model_type, sample, condition, resp) %>%
  summarise(n = length(resp)) %>% 
  ungroup %>% 
  unite(model, model, model_type, sep = "_") %>%
  unite(model, model, sample, sep = "@") %>% 
  complete(model, condition, resp, fill = list(n= 0)) %>%
  separate(model, c("model", "sample"), sep = "@") %>%
  separate(model, c("model", "model_type"), sep = "_") %>% 
  group_by(model, model_type, sample, condition) %>%
  mutate(tot = sum(n)) %>%
  ungroup %>% 
  mutate(perc = round(n / tot * 100, 0)) %>% 
  filter(resp != "subordinate") %>%
  group_by(model, model_type, condition) %>%
  summarise(mean_perc = mean(perc), sd = sd(perc)) %>%
  ungroup %>%
  rename(perc = mean_perc) %>%
  left_join(family_codes, by = c("model" = "models")) %>% 
  mutate(model = factor(model, levels = full_model_levels)) %>%
  #filter(model %in% c("bert-large-uncased", "roberta-large", "deberta-v2-xxlarge",
  #                    "babyberta-childes", "gpt2-xl", "elmo")) %>%
  #mutate(model = factor(model, levels = c("bert-large-uncased", "roberta-large", #"deberta-v2-xxlarge", "babyberta-childes", "gpt2-xl", "elmo"))) %>% 
  mutate(family = factor(family, levels = family_levels)) %>%
  rename(Condition = condition) %>%
    mutate(Condition = factor(Condition, levels = c("Control", "Lexical", "Semantic"),
                            labels = c("Control", "Verb-lexical", "Verb-event"))) %>%
  
  ggplot(aes(x = model, y = perc, pattern = Condition, fill = family)) +
  geom_bar_pattern(data = . %>% filter(model_type == "full"), 
                   stat = "identity", alpha = 0.6, width = .5,
    position = position_dodge(preserve = "single"),
     color = "dark grey", 
     pattern_fill = "dark grey",
     pattern_angle = 45,
                   pattern_density = 0.1,
                   pattern_spacing = 0.025,
                   pattern_key_scale_factor = 0.6) +
  geom_errorbar(data = . %>% 
                  filter(model_type == "downsample") %>%
                  mutate(model_type = "full"), aes(ymin = perc - sd, ymax = perc + sd),
                width=.2, position=position_dodge(1), size = 1, colour = "dark red") +
  geom_point(data = . %>% 
                  filter(model_type == "downsample") %>%
                  mutate(model_type = "full"), aes(y = perc), position = position_dodge(1), size = 4,
             colour = "dark red") +
  #facet_grid(~ model, scales = "free_x") +
  scale_y_continuous(limits = c(NA, 100), breaks = seq(0, 100, 25)) +
  #facet_grid(~ model, scales = "free_x") +
  geom_hline(yintercept=50, linetype="dashed", size = 0.7)+ 
  labs(y = "Dominant sense selection (%)", x = " ") +
  coord_flip() +
  theme_bw() +
  scale_fill_manual(values = my_palette) +
  guides(fill = "none") +
  theme(plot.title = element_text(size = 30), 
        axis.text.x = element_text(size=25, angle = 0, vjust = 0.7),
        axis.text.y = element_text(size=25),
        strip.text = element_text(size=20),
        legend.key.size = unit(3,"line"),
        legend.text = element_text(size = 30),
        legend.title = element_text(size = 30),
        axis.title.y = element_text(size=20, margin = margin(t = 0, r = 15, b = 0, l = 0)),
        axis.title.x = element_text(size=30, margin = margin(t = 30, r = 0, b = 0, l = 0)),
        plot.caption = element_text(hjust = 0, size = 25))
```

