name: transformers-child-wsd
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - mkl-service
  - pytorch-cuda=11.7
  - torchaudio
  - pytorch
  - torchvision
  - transformers=4.24
  - tensorflow-hub=0.12
  - scikit-learn
